Print the nodes names and IPs
* Print the nodes and IPs
* Refactor the init/join to their own files.
* Some cleanups

Signed-off-by: Alvaro Saurin <alvaro.saurin@gmail.com>

diff --git a/tests/e2e/Makefile b/tests/e2e/Makefile
--- a/tests/e2e/Makefile
+++ b/tests/e2e/Makefile
@@ -25,7 +25,11 @@ ci-tests:
 		echo "Running testsuite $$d" ; \
 		for i in $$d/[0-9]*-*.sh ; do \
 			echo "Running $$i" ; \
-			sh $$i ; \
+			$$i ; \
+			if [ $$? -ne 0 ] ; then \
+                echo ">>> FAILED: $$i"  ; \
+                exit 1  ; \
+            fi ; \
 		done ; \
 	done
 
